Seceng 260/sync with upstream (#36)
* add a github action to sync upstream branch to staging (#34)

* add a github action to sync upstream branch to staging

* remove trailing space from github action

* fix yamllint errors

* fix yaml lint issues

* relax yamllint config rules

* fix yamllint rules config

* lint App.tsx

* restore hopper config

* update yamllint rules config

* add selenium docker image to test yopass secret retrieval (#35)

* add selenium docker image to test yopass secret retrieval

* fix typo in circle config

* fix circle config

* update docker-compose config for yopass container

* add missing checkout step to docker compose task

* add setup_remote_docker config for circleci

* increase wait time and echo selenium result

* use f-string to populate yopass test url in selenium test

* debug docker compose ICC issue

* attempt to connect to yopass container via ip

* take out network debug lines from circleci config

* remove custom bridged network to debug

* remove old network config from docker compose

* update url for selenium test

* updated docker-compose config

* re-add internal bridged network to docker

* include no cache arg to docker compose

* update circleci config and remove comment from selenium script

* add newline to end of docker compose file

* add newline to end of docker compose file

* replace sleep with wait argument for docker compose and tear down containers when done

* update docker to wait for healthy containers and re-added sleep and updated github action to raise a PR on sync

* remove trailing space for github action

* revert file perms for hopper config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,6 +42,30 @@ build_docker_image: &build_docker_image
         paths:
           - '*.tar'
 
+test_yopass_secret: &test_yopass_secret
+  executor: docker-container
+  steps:
+    - attach_workspace:
+        at: /tmp/workspace
+    - setup_remote_docker:
+          docker_layer_caching: true
+    - checkout
+    - run:
+        name: Add and retrieve test secret
+        command: |
+          docker compose build --no-cache
+          docker compose up -d --wait
+          sleep 5
+          yopass_result=$(docker compose logs selenium_browser | cut -d '|' -f2 | xargs 2>&1)
+          echo $yopass_result
+          if [ "$yopass_result" = "PASS" ]; then
+            echo "Secret successfully generated and retrieved from Yopass"
+          else
+            echo "Secret generation and retrieval failed!"
+            exit 1
+          fi
+          docker compose down
+
 push_image_to_ecr: &push_image_to_ecr
   executor: docker-container
   steps:
@@ -63,19 +87,24 @@ filter_master_branch: &filter_master_branch
   filters:
     branches:
       only:
-      - master
+        - master
 
 filter_staging_branch: &filter_staging_branch
   filters:
     branches:
       only:
-      - staging
+        - staging
 
 jobs:
   build_docker_image:
     executor: docker-container
     resource_class: small
     <<: *build_docker_image
+
+  add_and_retrieve_test_secret:
+    executor: docker-container
+    resource_class: small
+    <<: *test_yopass_secret
 
   push_ecr_image_to_staging:
     executor: docker-container
@@ -97,13 +126,17 @@ workflows:
     jobs:
       - build_docker_image:
           <<: *global_context
+      - add_and_retrieve_test_secret:
+          <<: *global_context
+          requires:
+            - build_docker_image
       - push_ecr_image_to_staging:
           <<: *global_context
           <<: *filter_staging_branch
           requires:
-            - build_docker_image
+            - add_and_retrieve_test_secret
       - push_ecr_image_to_production:
           <<: *global_context
           <<: *filter_master_branch
           requires:
-            - build_docker_image
+            - add_and_retrieve_test_secret
