core-910: display built commit on home

diff --git a/CI/templates/deploy.yaml b/CI/templates/deploy.yaml
--- a/CI/templates/deploy.yaml
+++ b/CI/templates/deploy.yaml
@@ -29,12 +29,38 @@ jobs:
                   --expression "s/elvid-redirect-uri-value/onetime.${{ parameters.elviaDomain  }}/"
                   --expression "s/elvid-scope-value/${{ parameters.elvidScope }}/"
                   $(Pipeline.Workspace)/CI/manifest.yaml > manifest_modified.yaml
+
+                  cat --show-all manifest_modified.yaml
             - task: Bash@3
-              displayName: "Display Manifest File"
+              displayName: "Obtain Short Commit Hash"
+              workingDirectory: $(Build.SourcesDirectory)
+              inputs:
+                targetType: "inline"
+                script: |
+                  # https://stackoverflow.com/a/62469078
+                  shortCommitHash=`git rev-parse --short=7 HEAD`
+                  echo ""
+                  echo "Full Hash:  $(Build.SourceVersion)"
+                  echo "Short Hash: $shortCommitHash"
+                  echo ""
+                  if [[ $(Build.SourceVersion) != $shortCommitHash* ]]; then
+                    echo "--> Hashes do not match! Aborting."
+                    exit 1
+                  fi
+                  echo "--> Hashes match. Storing short hash for subsequent steps."
+                  ## Store variable for subsequent steps.
+                  echo "##vso[task.setvariable variable=shortCommitHash]$shortCommitHash"
+            - task: Bash@3
+              displayName: "Append Git Commit to React Environment File"
               inputs:
                 targetType: "inline"
                 script: >
-                  cat --show-all manifest_modified.yaml
+                  sed
+                  --in-place
+                  --expression "s/gitCommitValue/$(shortCommitHash)/"
+                  $(Pipeline.Workspace)/website/.env
+
+                  cat --show-all $(Pipeline.Workspace)/website/.env
             - task: KubernetesManifest@0
               displayName: "Deploy"
               inputs:
